# Generated by Django 4.1.4 on 2023-03-07 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TransportLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_destination', to='trips.destination')),
                ('departure_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_destination', to='trips.destination')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.travelroute')),
                ('trip_transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='trips.destinationtransport')),
            ],
        ),
    ]
