# Generated by Django 4.1.4 on 2023-03-07 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_destinationtransport_transportleg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinationtransport',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='transportleg',
            name='arrival_destination',
        ),
        migrations.RemoveField(
            model_name='transportleg',
            name='departure_destination',
        ),
        migrations.AddField(
            model_name='destinationtransport',
            name='arrival_destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='arrival_destination', to='trips.destination'),
        ),
        migrations.AddField(
            model_name='destinationtransport',
            name='departure_destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departure_destination', to='trips.destination'),
        ),
        migrations.AddField(
            model_name='destinationtransport',
            name='transport_legs',
            field=models.ManyToManyField(to='trips.transportleg'),
        ),
    ]
