# Generated by Django 4.1.4 on 2023-03-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_alter_destinationtransport_transport_legs'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='photo_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
