# Generated by Django 4.1.4 on 2023-03-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_city_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=17, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=17, max_digits=20, null=True),
        ),
    ]
