# Generated by Django 4.1.4 on 2023-03-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_airport'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='skyscanner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
