# Generated by Django 4.1.4 on 2023-03-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_city_skyscanner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='photo_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
