# Generated by Django 4.1.4 on 2023-03-16 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_alter_city_photo_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Airport',
        ),
    ]
