# Generated by Django 4.1.4 on 2023-03-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0014_remove_destination_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='nights',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='order',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='start_date',
        ),
        migrations.AddField(
            model_name='destination',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
