# Generated by Django 4.1.4 on 2023-03-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0015_remove_destination_nights_remove_destination_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
