# Generated by Django 4.1.4 on 2023-03-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0016_trip_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='start_date',
        ),
        migrations.AddField(
            model_name='destination',
            name='nights',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='destination',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
