# Generated by Django 4.1.4 on 2023-03-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0019_remove_destination_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
