# Generated by Django 4.1.4 on 2023-03-30 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0020_destination_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='end_date',
        ),
    ]
