# Generated by Django 4.1.4 on 2023-04-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0022_destination_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
