# Generated by Django 4.1.4 on 2023-04-02 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0023_destination_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='start_date',
        ),
    ]
