# Generated by Django 4.1.4 on 2023-04-18 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0026_city_budget_city_climate_city_food_culture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='skyscanner_id',
        ),
    ]
