# Generated by Django 4.1.4 on 2023-04-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0028_remove_city_budget_remove_city_food_culture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='accom_budget',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='climate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='food_budget',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='accom_budget',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='climate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='food_budget',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='journey_times',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
