# Generated by Django 4.1.4 on 2023-03-22 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0013_alter_trip_budget_alter_trip_climate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hotel_url', models.URLField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=17, max_digits=20, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=17, max_digits=20, null=True)),
                ('star_rating', models.IntegerField(choices=[('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')])),
                ('custom_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('image_urls', models.TextField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.destination')),
            ],
        ),
    ]
