# Generated by Django 4.1.4 on 2023-01-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_delete_book_delete_building'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('alpha2code', models.CharField(max_length=3)),
                ('currency', models.CharField(max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
