# Generated by Django 4.1.4 on 2023-01-09 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_country_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='alpha2code',
            new_name='alpha3code',
        ),
    ]
