# Generated by Django 4.1.4 on 2023-01-09 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_alpha2code_country_alpha3code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='alpha3code',
            new_name='alpha2code',
        ),
    ]
