# Generated by Django 4.1.4 on 2023-02-05 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_city_lat_city_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='city',
            name='lng',
        ),
    ]
