# Generated by Django 4.1.4 on 2023-02-27 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_trainroutes_ferryroutes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FerryRoutes',
            new_name='FerryRoute',
        ),
        migrations.RenameModel(
            old_name='TrainRoutes',
            new_name='TrainRoute',
        ),
    ]
