# Generated by Django 4.1.4 on 2023-02-28 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_rename_ferryroutes_ferryroute_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('type', models.CharField(choices=[('train', 'Train'), ('ferry', 'Ferry'), ('bus', 'Bus')], max_length=10)),
                ('end_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_travel_route', to='myapp.city')),
                ('start_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_travel_route', to='myapp.city')),
            ],
        ),
    ]
