# Generated by Django 4.1.4 on 2023-01-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_alpha3code_country_alpha2code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='alpha2code',
            field=models.CharField(max_length=2),
        ),
    ]
