# Generated by Django 4.1.4 on 2023-02-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_profile_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='is_interrail',
            field=models.BooleanField(default=False),
        ),
    ]
