# Generated by Django 4.1.4 on 2023-02-12 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_destination_country_destination_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.country'),
        ),
    ]
