# Generated by Django 4.1.4 on 2023-02-25 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_profile_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.city'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='myapp.country'),
        ),
    ]
