# Generated by Django 4.1.4 on 2023-02-28 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_travelroute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainroute',
            name='end_city',
        ),
        migrations.RemoveField(
            model_name='trainroute',
            name='start_city',
        ),
        migrations.DeleteModel(
            name='FerryRoute',
        ),
        migrations.DeleteModel(
            name='TrainRoute',
        ),
    ]
