# Generated by Django 4.1.4 on 2023-03-16 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0010_delete_airport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('iata_code', models.CharField(max_length=3)),
                ('distance', models.DecimalField(decimal_places=17, max_digits=20)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.city')),
            ],
        ),
    ]
