# Generated by Django 4.1.4 on 2023-03-16 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_delete_airport'),
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound')], max_length=10)),
                ('departure_datetime', models.DateTimeField()),
                ('arrival_datetime', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_airport', to='flights.airport')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_airport', to='flights.airport')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.destination')),
            ],
        ),
        migrations.CreateModel(
            name='SubFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_departure_datetime', models.DateTimeField()),
                ('sub_arrival_datetime', models.DateTimeField()),
                ('sub_duration', models.IntegerField()),
                ('airline', models.CharField(max_length=50)),
                ('master_flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flight')),
                ('sub_arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_arrival_airport', to='flights.airport')),
                ('sub_departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_departure_airport', to='flights.airport')),
            ],
        ),
    ]
