# Generated by Django 4.1.4 on 2023-03-18 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_delete_airport'),
        ('flights', '0003_remove_flight_destination_remove_subflight_airline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='trip',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='trips.trip'),
        ),
    ]
