# Generated by Django 4.1.4 on 2023-03-23 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0013_alter_trip_budget_alter_trip_climate_and_more'),
        ('flights', '0004_alter_flight_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='city',
        ),
        migrations.RemoveField(
            model_name='airport',
            name='distance',
        ),
        migrations.AddField(
            model_name='airport',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trips.country'),
        ),
        migrations.AddField(
            model_name='airport',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=17, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=17, max_digits=20, null=True),
        ),
    ]
