# Generated by Django 4.1.4 on 2023-03-23 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0013_alter_trip_budget_alter_trip_climate_and_more'),
        ('flights', '0005_remove_airport_city_remove_airport_distance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterrailAirport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flights.airport')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trips.city')),
            ],
        ),
    ]
