# Generated by Django 4.1.4 on 2023-03-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_interrailairport'),
    ]

    operations = [
        migrations.AddField(
            model_name='interrailairport',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=17, max_digits=20, null=True),
        ),
    ]
