# Generated by Django 4.1.4 on 2023-03-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_interrailairport_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='number_connections',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='SubFlight',
        ),
    ]
